"""Curated public figures -> CLIP text prompts with interpretable attributes."""
import json

# (name, short descriptor, field, era, region)
P = [
 ("Marie Curie","physicist and chemist, discovered radium","science","historical","Europe"),
 ("Albert Einstein","theoretical physicist","science","historical","Europe"),
 ("Isaac Newton","mathematician and physicist","science","historical","Europe"),
 ("Charles Darwin","naturalist","science","historical","Europe"),
 ("Ada Lovelace","mathematician, first programmer","science","historical","Europe"),
 ("Nikola Tesla","electrical engineer and inventor","science","historical","Europe"),
 ("Srinivasa Ramanujan","mathematician","science","historical","Asia"),
 ("C. V. Raman","physicist, Nobel laureate","science","historical","Asia"),
 ("Rosalind Franklin","chemist, X-ray crystallographer","science","historical","Europe"),
 ("Alan Turing","mathematician and computer scientist","science","historical","Europe"),
 ("Emmy Noether","mathematician","science","historical","Europe"),
 ("Richard Feynman","theoretical physicist","science","historical","Americas"),
 ("Barbara McClintock","geneticist","science","historical","Americas"),
 ("Dorothy Hodgkin","chemist, Nobel laureate","science","historical","Europe"),
 ("Katherine Johnson","mathematician at NASA","science","historical","Americas"),
 ("Jane Goodall","primatologist","science","contemporary","Europe"),
 ("Jennifer Doudna","biochemist, CRISPR pioneer","science","contemporary","Americas"),
 ("Emmanuelle Charpentier","microbiologist, CRISPR pioneer","science","contemporary","Europe"),
 ("Donna Strickland","physicist, Nobel laureate","science","contemporary","Americas"),
 ("Andrea Ghez","astronomer, Nobel laureate","science","contemporary","Americas"),
 ("Frances Arnold","chemical engineer, Nobel laureate","science","contemporary","Americas"),
 ("Carlo Rovelli","theoretical physicist and writer","science","contemporary","Europe"),
 ("Brian Cox","physicist and broadcaster","science","contemporary","Europe"),
 ("Neil deGrasse Tyson","astrophysicist and communicator","science","contemporary","Americas"),
 ("Venki Ramakrishnan","structural biologist, Nobel laureate","science","contemporary","Asia"),
 ("Abhijit Banerjee","economist, Nobel laureate","science","contemporary","Asia"),

 ("Geoffrey Hinton","computer scientist, deep learning pioneer","tech","contemporary","Americas"),
 ("Yann LeCun","computer scientist, convolutional networks","tech","contemporary","Europe"),
 ("Yoshua Bengio","computer scientist, deep learning pioneer","tech","contemporary","Americas"),
 ("Fei-Fei Li","computer scientist, ImageNet","tech","contemporary","Americas"),
 ("Demis Hassabis","AI researcher, Nobel laureate","tech","contemporary","Europe"),
 ("Andrej Karpathy","AI researcher and educator","tech","contemporary","Americas"),
 ("Grace Hopper","computer scientist and naval officer","tech","historical","Americas"),
 ("Tim Berners-Lee","inventor of the World Wide Web","tech","contemporary","Europe"),
 ("Linus Torvalds","software engineer, created Linux","tech","contemporary","Europe"),
 ("Margaret Hamilton","software engineer, Apollo guidance","tech","historical","Americas"),
 ("Satya Nadella","technology executive","tech","contemporary","Asia"),
 ("Sundar Pichai","technology executive","tech","contemporary","Asia"),
 ("Jensen Huang","technology executive, semiconductors","tech","contemporary","Asia"),
 ("Elon Musk","entrepreneur, aerospace and automotive","tech","contemporary","Americas"),
 ("Steve Jobs","technology entrepreneur","tech","historical","Americas"),
 ("Bill Gates","software entrepreneur and philanthropist","tech","contemporary","Americas"),
 ("Sam Altman","technology executive","tech","contemporary","Americas"),
 ("Nandan Nilekani","technology entrepreneur","tech","contemporary","Asia"),
 ("Narayana Murthy","software entrepreneur","tech","contemporary","Asia"),
 ("Radia Perlman","network engineer, spanning tree protocol","tech","contemporary","Americas"),

 ("Ludwig van Beethoven","composer","music","historical","Europe"),
 ("Wolfgang Amadeus Mozart","composer","music","historical","Europe"),
 ("Johann Sebastian Bach","composer","music","historical","Europe"),
 ("Frédéric Chopin","composer and pianist","music","historical","Europe"),
 ("Ravi Shankar","sitar maestro","music","historical","Asia"),
 ("M. S. Subbulakshmi","Carnatic vocalist","music","historical","Asia"),
 ("Lata Mangeshkar","playback singer","music","historical","Asia"),
 ("A. R. Rahman","film composer","music","contemporary","Asia"),
 ("Zakir Hussain","tabla virtuoso","music","contemporary","Asia"),
 ("Miles Davis","jazz trumpeter","music","historical","Americas"),
 ("Ella Fitzgerald","jazz singer","music","historical","Americas"),
 ("John Coltrane","jazz saxophonist","music","historical","Americas"),
 ("Nina Simone","singer and pianist","music","historical","Americas"),
 ("Bob Dylan","songwriter, Nobel laureate","music","historical","Americas"),
 ("Freddie Mercury","rock singer","music","historical","Europe"),
 ("David Bowie","musician","music","historical","Europe"),
 ("Aretha Franklin","soul singer","music","historical","Americas"),
 ("Bob Marley","reggae musician","music","historical","Americas"),
 ("Fela Kuti","Afrobeat musician","music","historical","Africa"),
 ("Miriam Makeba","singer and activist","music","historical","Africa"),
 ("Beyoncé","singer and performer","music","contemporary","Americas"),
 ("Taylor Swift","singer-songwriter","music","contemporary","Americas"),
 ("Kendrick Lamar","rapper, Pulitzer laureate","music","contemporary","Americas"),
 ("Adele","singer-songwriter","music","contemporary","Europe"),
 ("Björk","musician and producer","music","contemporary","Europe"),
 ("Yo-Yo Ma","cellist","music","contemporary","Americas"),
 ("Burna Boy","Afrobeats musician","music","contemporary","Africa"),
 ("Rosalía","singer and producer","music","contemporary","Europe"),
 ("Hans Zimmer","film composer","music","contemporary","Europe"),
 ("Nusrat Fateh Ali Khan","qawwali singer","music","historical","Asia"),

 ("Charlie Chaplin","actor and filmmaker","film","historical","Europe"),
 ("Akira Kurosawa","film director","film","historical","Asia"),
 ("Alfred Hitchcock","film director","film","historical","Europe"),
 ("Satyajit Ray","film director","film","historical","Asia"),
 ("Federico Fellini","film director","film","historical","Europe"),
 ("Ingmar Bergman","film director","film","historical","Europe"),
 ("Audrey Hepburn","actress","film","historical","Europe"),
 ("Marlon Brando","actor","film","historical","Americas"),
 ("Toshiro Mifune","actor","film","historical","Asia"),
 ("Amitabh Bachchan","actor","film","contemporary","Asia"),
 ("Meryl Streep","actress","film","contemporary","Americas"),
 ("Denzel Washington","actor","film","contemporary","Americas"),
 ("Martin Scorsese","film director","film","contemporary","Americas"),
 ("Steven Spielberg","film director","film","contemporary","Americas"),
 ("Christopher Nolan","film director","film","contemporary","Europe"),
 ("Greta Gerwig","film director and actress","film","contemporary","Americas"),
 ("Bong Joon-ho","film director","film","contemporary","Asia"),
 ("Hayao Miyazaki","animator and film director","film","contemporary","Asia"),
 ("Pedro Almodóvar","film director","film","contemporary","Europe"),
 ("Viola Davis","actress","film","contemporary","Americas"),
 ("Cate Blanchett","actress","film","contemporary","Oceania"),
 ("Michelle Yeoh","actress","film","contemporary","Asia"),
 ("Mira Nair","film director","film","contemporary","Asia"),
 ("Wes Anderson","film director","film","contemporary","Americas"),
 ("Agnès Varda","film director","film","historical","Europe"),

 ("Pelé","footballer","sport","historical","Americas"),
 ("Diego Maradona","footballer","sport","historical","Americas"),
 ("Muhammad Ali","boxer","sport","historical","Americas"),
 ("Jesse Owens","sprinter","sport","historical","Americas"),
 ("Nadia Comăneci","gymnast","sport","historical","Europe"),
 ("Kapil Dev","cricketer","sport","historical","Asia"),
 ("Sunil Gavaskar","cricketer","sport","historical","Asia"),
 ("Sachin Tendulkar","cricketer","sport","contemporary","Asia"),
 ("Virat Kohli","cricketer","sport","contemporary","Asia"),
 ("P. V. Sindhu","badminton player","sport","contemporary","Asia"),
 ("Mary Kom","boxer","sport","contemporary","Asia"),
 ("Neeraj Chopra","javelin thrower","sport","contemporary","Asia"),
 ("Lionel Messi","footballer","sport","contemporary","Americas"),
 ("Cristiano Ronaldo","footballer","sport","contemporary","Europe"),
 ("Serena Williams","tennis player","sport","contemporary","Americas"),
 ("Roger Federer","tennis player","sport","contemporary","Europe"),
 ("Rafael Nadal","tennis player","sport","contemporary","Europe"),
 ("Usain Bolt","sprinter","sport","contemporary","Americas"),
 ("Simone Biles","gymnast","sport","contemporary","Americas"),
 ("Michael Jordan","basketball player","sport","historical","Americas"),
 ("LeBron James","basketball player","sport","contemporary","Americas"),
 ("Eliud Kipchoge","marathon runner","sport","contemporary","Africa"),
 ("Magnus Carlsen","chess grandmaster","sport","contemporary","Europe"),
 ("Viswanathan Anand","chess grandmaster","sport","contemporary","Asia"),
 ("Megan Rapinoe","footballer","sport","contemporary","Americas"),

 ("Mahatma Gandhi","independence leader","politics","historical","Asia"),
 ("Nelson Mandela","statesman and anti-apartheid leader","politics","historical","Africa"),
 ("Martin Luther King Jr.","civil rights leader","politics","historical","Americas"),
 ("Winston Churchill","statesman","politics","historical","Europe"),
 ("Abraham Lincoln","president","politics","historical","Americas"),
 ("B. R. Ambedkar","jurist and social reformer","politics","historical","Asia"),
 ("Jawaharlal Nehru","statesman","politics","historical","Asia"),
 ("Indira Gandhi","prime minister","politics","historical","Asia"),
 ("Eleanor Roosevelt","diplomat and human rights advocate","politics","historical","Americas"),
 ("Rosa Parks","civil rights activist","politics","historical","Americas"),
 ("Sojourner Truth","abolitionist","politics","historical","Americas"),
 ("Kwame Nkrumah","independence leader","politics","historical","Africa"),
 ("Simón Bolívar","independence leader","politics","historical","Americas"),
 ("Angela Merkel","chancellor","politics","contemporary","Europe"),
 ("Barack Obama","president","politics","contemporary","Americas"),
 ("Jacinda Ardern","prime minister","politics","contemporary","Oceania"),
 ("Malala Yousafzai","education activist, Nobel laureate","politics","contemporary","Asia"),
 ("Greta Thunberg","climate activist","politics","contemporary","Europe"),
 ("Wangari Maathai","environmentalist, Nobel laureate","politics","historical","Africa"),
 ("Ellen Johnson Sirleaf","president, Nobel laureate","politics","contemporary","Africa"),
 ("Ruth Bader Ginsburg","supreme court justice","politics","historical","Americas"),

 ("William Shakespeare","playwright and poet","literature","historical","Europe"),
 ("Jane Austen","novelist","literature","historical","Europe"),
 ("Leo Tolstoy","novelist","literature","historical","Europe"),
 ("Fyodor Dostoevsky","novelist","literature","historical","Europe"),
 ("Rabindranath Tagore","poet, Nobel laureate","literature","historical","Asia"),
 ("Virginia Woolf","novelist","literature","historical","Europe"),
 ("James Baldwin","writer and essayist","literature","historical","Americas"),
 ("Gabriel García Márquez","novelist, Nobel laureate","literature","historical","Americas"),
 ("Maya Angelou","poet and memoirist","literature","historical","Americas"),
 ("Jorge Luis Borges","writer","literature","historical","Americas"),
 ("Chinua Achebe","novelist","literature","historical","Africa"),
 ("Toni Morrison","novelist, Nobel laureate","literature","historical","Americas"),
 ("George Orwell","novelist and essayist","literature","historical","Europe"),
 ("Franz Kafka","writer","literature","historical","Europe"),
 ("Haruki Murakami","novelist","literature","contemporary","Asia"),
 ("Chimamanda Ngozi Adichie","novelist","literature","contemporary","Africa"),
 ("Arundhati Roy","novelist and essayist","literature","contemporary","Asia"),
 ("Salman Rushdie","novelist","literature","contemporary","Asia"),
 ("Margaret Atwood","novelist","literature","contemporary","Americas"),
 ("Ocean Vuong","poet and novelist","literature","contemporary","Americas"),

 ("Leonardo da Vinci","polymath, painter and engineer","art","historical","Europe"),
 ("Michelangelo","sculptor and painter","art","historical","Europe"),
 ("Vincent van Gogh","painter","art","historical","Europe"),
 ("Frida Kahlo","painter","art","historical","Americas"),
 ("Pablo Picasso","painter","art","historical","Europe"),
 ("Claude Monet","painter","art","historical","Europe"),
 ("Katsushika Hokusai","woodblock printmaker","art","historical","Asia"),
 ("Georgia O'Keeffe","painter","art","historical","Americas"),
 ("Salvador Dalí","painter","art","historical","Europe"),
 ("Amrita Sher-Gil","painter","art","historical","Asia"),
 ("Zaha Hadid","architect","art","historical","Asia"),
 ("Le Corbusier","architect","art","historical","Europe"),
 ("Ai Weiwei","artist and activist","art","contemporary","Asia"),
 ("Yayoi Kusama","artist","art","contemporary","Asia"),
 ("Banksy","street artist","art","contemporary","Europe"),
 ("Anish Kapoor","sculptor","art","contemporary","Asia"),
 ("Kehinde Wiley","painter","art","contemporary","Americas"),
 ("Bjarke Ingels","architect","art","contemporary","Europe"),
 ("Balkrishna Doshi","architect, Pritzker laureate","art","contemporary","Asia"),
 ("Cindy Sherman","photographer","art","contemporary","Americas"),
]

STEM = {"science", "tech"}


def main():
    out = []
    for i, (name, desc, field, era, region) in enumerate(P):
        out.append({
            "id": f"p{i:03d}",
            "name": name,
            "desc": desc,
            "field": field,
            "era": era,
            "region": region,
            "stem": field in STEM,
            "prompt": f"a portrait photograph of {name}, {desc}",
        })
    with open("assets/people.json", "w") as f:
        json.dump(out, f)
    from collections import Counter
    print(len(out), "people")
    print(Counter(o["field"] for o in out))
    print(Counter(o["era"] for o in out))
    print(Counter(o["region"] for o in out))


if __name__ == "__main__":
    main()
